Working
kelibst/do-it pull request #1
Opened 2020-08-10 23:06 UTC by kelibst

> A basic JavaScript To do app for creating tasks and adding to do's.
Read more on the project specifications on [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list)

- Loads Contents directly to the page using Javascript.
- Users can add Task. Todos are grouped under tasks
- Responsive

2020-08-11 12:01 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi team :hand: 
Nice job so far in this project :clap:, I really liked your UI 
But we need to make some changes before moving on.

- [ ] The user should be able to edit the details of a to-do item. Right now you application does not have this feature.

Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-08-11 12:01 UTC, Torres-ssf commented on .stickler.yml
> +# find full documentation here: https://stickler-ci.com/docs
- [ ] You can delete the stickler.yml file. You are already using Github actions, so using the stickler is not necessary.

2020-08-11 19:06 UTC, Forison requested changes
## Status:: Changes Required❌

# 🙋‍♂️ Team 

* [ ]  I have tried to use your application locally and by using the two live links you provided in the readme. 
- [ Here is a link to the video of my findings](https://www.loom.com/share/60600cde169c46709dfc279c5f7c149b).
### Kindly make, make the address the issue and submit a re-review🧒.

#### Happy coding👨‍💻

Addo Forison

2020-08-13 01:39 UTC, Ispirett approved these changes
# Status Approved :+1: 
Great work! folks with all the changes made and on completing this project. :+1: 

You can change the add task button to add projects.

2020-08-24 07:41 UTC, merged